### ISSUE TITLE
Handle "Too many publishes in progress" exception

### ISSUE THREAD

**Issue by vityaman** [vityaman-edu/nexo-hub#59]
```
nexohub-fake-users   | Exception in thread "pool-1-thread-12" Too many publishes in progress (32202)
nexohub-fake-users   |  at org.eclipse.paho.client.mqttv3.internal.ClientState.send(ClientState.java:524)
nexohub-fake-users   |  at org.eclipse.paho.client.mqttv3.internal.ClientComms.internalSend(ClientComms.java:161)
nexohub-fake-users   |  at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:191)
nexohub-fake-users   |  at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1251)
nexohub-fake-users   |  at org.eclipse.paho.client.mqttv3.MqttClient.publish(MqttClient.java:570)
nexohub-fake-users   |  at org.eclipse.paho.client.mqttv3.MqttClient.publish(MqttClient.java:562)
nexohub-fake-users   |  at org.vivlaniv.nexohub.ScenarioKt.authUser(Scenario.kt:132)
nexohub-fake-users   |  at org.vivlaniv.nexohub.ScenarioKt$startUserScenario$onSuccessRegistration$1.invoke(Scenario.kt:58)
nexohub-fake-users   |  at org.vivlaniv.nexohub.ScenarioKt$startUserScenario$onSuccessRegistration$1.invoke(Scenario.kt:56)
nexohub-fake-users   |  at org.vivlaniv.nexohub.ScenarioKt$registerUser$$inlined$subscribe$1$1.invokeSuspend(Mqtt.kt:37)
nexohub-fake-users   |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
nexohub-fake-users   |  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
nexohub-fake-users   |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
nexohub-fake-users   |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
nexohub-fake-users   |  at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Andryss** [comment]
Ошибка не воспроизводится
